//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuanAo.Entity.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Import
    {
        public int Import_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Money { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual tbl_Supplier tbl_Supplier { get; set; }
    }
}
