//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuanAo.Entity.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.Images = new HashSet<Image>();
            this.tbl_ImportDetail = new HashSet<tbl_ImportDetail>();
            this.tbl_OrderDetial = new HashSet<tbl_OrderDetial>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public int Type_ID { get; set; }
        public int Style_ID { get; set; }
        public int Producer_ID { get; set; }
        public int Supplier_ID { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public Nullable<double> Price_Import { get; set; }
        public double Price_Export { get; set; }
        public Nullable<int> Amount { get; set; }
        public double Weight { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SizeID { get; set; }
        public int Order { get; set; }
        public Nullable<int> Quantium { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Size Size1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ImportDetail> tbl_ImportDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderDetial> tbl_OrderDetial { get; set; }
        public virtual tbl_Producer tbl_Producer { get; set; }
        public virtual tbl_Style tbl_Style { get; set; }
        public virtual tbl_Supplier tbl_Supplier { get; set; }
        public virtual tbl_Type tbl_Type { get; set; }
    }
}
