//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuanAo.Entity.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Order()
        {
            this.tbl_OrderDetial = new HashSet<tbl_OrderDetial>();
        }
    
        public string Order_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int Pay_ID { get; set; }
        public int Transport_ID { get; set; }
        public string Name_Received { get; set; }
        public string Address_Received { get; set; }
        public Nullable<int> Phone_Received { get; set; }
        public string Name_Pay { get; set; }
        public string Address_Pay { get; set; }
        public Nullable<int> Phone_Pay { get; set; }
        public string Mesage { get; set; }
        public Nullable<double> VAT_Gift { get; set; }
        public Nullable<double> SumWeight { get; set; }
        public Nullable<double> VAT_Transport { get; set; }
        public Nullable<double> SumMoney { get; set; }
        public string State { get; set; }
    
        public virtual tbl_Payment tbl_Payment { get; set; }
        public virtual tbl_Transport tbl_Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderDetial> tbl_OrderDetial { get; set; }
    }
}
