//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanQuanAo.Entity.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public int AccountID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Power { get; set; }
        public int RoleID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
