//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.bqa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.bqa.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua ngay.
        /// </summary>
        internal static string actionBuy {
            get {
                return ResourceManager.GetString("actionBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc theo giá.
        /// </summary>
        internal static string actionFilter {
            get {
                return ResourceManager.GetString("actionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp theo.
        /// </summary>
        internal static string actionFilter1 {
            get {
                return ResourceManager.GetString("actionFilter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu.
        /// </summary>
        internal static string actionFilter2 {
            get {
                return ResourceManager.GetString("actionFilter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string actionFilter3 {
            get {
                return ResourceManager.GetString("actionFilter3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại khủng trong tuần.
        /// </summary>
        internal static string actionSale {
            get {
                return ResourceManager.GetString("actionSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        internal static string actionSee {
            get {
                return ResourceManager.GetString("actionSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi câu trả lời.
        /// </summary>
        internal static string actionSubmit {
            get {
                return ResourceManager.GetString("actionSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        internal static string addCart {
            get {
                return ResourceManager.GetString("addCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập để nhận ngay ưu đãi.
        /// </summary>
        internal static string btnActionLogin {
            get {
                return ResourceManager.GetString("btnActionLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật giỏ hàng.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        internal static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string btnOkLogin {
            get {
                return ResourceManager.GetString("btnOkLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bấm đây.
        /// </summary>
        internal static string clickHere {
            get {
                return ResourceManager.GetString("clickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm đây để đăng nhập.
        /// </summary>
        internal static string clickLogin {
            get {
                return ResourceManager.GetString("clickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu.
        /// </summary>
        internal static string colorProduct {
            get {
                return ResourceManager.GetString("colorProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string costProduct {
            get {
                return ResourceManager.GetString("costProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hoặc đăng ký ngay để nhận nhiều dịch vụ ưu đãi..
        /// </summary>
        internal static string detail1 {
            get {
                return ResourceManager.GetString("detail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linh hoạt trong cách thức thanh toán.
        /// </summary>
        internal static string detail2 {
            get {
                return ResourceManager.GetString("detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các chương trình ưu đãi theo tuần, tháng và năm.
        /// </summary>
        internal static string detail3 {
            get {
                return ResourceManager.GetString("detail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8h sáng - 9h tối.
        /// </summary>
        internal static string detail4 {
            get {
                return ResourceManager.GetString("detail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có rất nhiều cách để có thể liên hệ với chúng tôi. Bạn có thể liên hệ qua e-mail, điện thoại, hoặc theo dõi chúng tôi trên fanpage.
        /// </summary>
        internal static string detailContact {
            get {
                return ResourceManager.GetString("detailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string detailContact2 {
            get {
                return ResourceManager.GetString("detailContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twetter.
        /// </summary>
        internal static string detailContact3 {
            get {
                return ResourceManager.GetString("detailContact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiết khấu.
        /// </summary>
        internal static string detailPay {
            get {
                return ResourceManager.GetString("detailPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí vận chuyển.
        /// </summary>
        internal static string detailTranport {
            get {
                return ResourceManager.GetString("detailTranport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá (thấp - cao).
        /// </summary>
        internal static string filterCost1 {
            get {
                return ResourceManager.GetString("filterCost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá (cao - thấp).
        /// </summary>
        internal static string filterCost2 {
            get {
                return ResourceManager.GetString("filterCost2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mặc định.
        /// </summary>
        internal static string filterDefault {
            get {
                return ResourceManager.GetString("filterDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm (A-Z).
        /// </summary>
        internal static string filterName1 {
            get {
                return ResourceManager.GetString("filterName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm (Z-A).
        /// </summary>
        internal static string filterName2 {
            get {
                return ResourceManager.GetString("filterName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có tài khoản?.
        /// </summary>
        internal static string hasAcount {
            get {
                return ResourceManager.GetString("hasAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string idProduct {
            get {
                return ResourceManager.GetString("idProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string langEnglish {
            get {
                return ResourceManager.GetString("langEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string langVietnammese {
            get {
                return ResourceManager.GetString("langVietnammese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi số lượng.
        /// </summary>
        internal static string lbChangeAmount {
            get {
                return ResourceManager.GetString("lbChangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mời bạn vui lòng điền các trường thông tin bên dưới.
        /// </summary>
        internal static string lbComment {
            get {
                return ResourceManager.GetString("lbComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string lbFogotPass {
            get {
                return ResourceManager.GetString("lbFogotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi chúng tôi.
        /// </summary>
        internal static string lbFollow {
            get {
                return ResourceManager.GetString("lbFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string lbForgotPass {
            get {
                return ResourceManager.GetString("lbForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Định dạng nhập vào không chính xác. Vui lòng nhập lại..
        /// </summary>
        internal static string lbFormat {
            get {
                return ResourceManager.GetString("lbFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên.
        /// </summary>
        internal static string lbN {
            get {
                return ResourceManager.GetString("lbN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản!.
        /// </summary>
        internal static string lbNoAccount {
            get {
                return ResourceManager.GetString("lbNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu bạn đã có tài khoản, đăng nhập vào ô dưới đây để được giảm tối đa 10% phí vận chuyển. Nếu bạn là khách hàng mới hãy điền các thông tin vào bảng thông tin &amp;amp; phiên giao hàng..
        /// </summary>
        internal static string lbNote {
            get {
                return ResourceManager.GetString("lbNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đặt hàng thành công cảm ơn bạn nhân viên giao hàng sẽ gọi điện cho bạn để xác nhận.
        /// </summary>
        internal static string lbOk {
            get {
                return ResourceManager.GetString("lbOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string lbQuanti {
            get {
                return ResourceManager.GetString("lbQuanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        internal static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm đây để đăng ký.
        /// </summary>
        internal static string lbRegisterNow {
            get {
                return ResourceManager.GetString("lbRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8h - 21h Từ thứ 2 đến thứ chủ nhật.
        /// </summary>
        internal static string lbTime {
            get {
                return ResourceManager.GetString("lbTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ mở cửa.
        /// </summary>
        internal static string lbTimeOpen {
            get {
                return ResourceManager.GetString("lbTimeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIỄN PHÍ SHIP VỚI ĐƠN HÀNG TỪ 500K.
        /// </summary>
        internal static string lbTop {
            get {
                return ResourceManager.GetString("lbTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string lbX {
            get {
                return ResourceManager.GetString("lbX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string menuContact {
            get {
                return ResourceManager.GetString("menuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string menuHome {
            get {
                return ResourceManager.GetString("menuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        internal static string menuNew {
            get {
                return ResourceManager.GetString("menuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại.
        /// </summary>
        internal static string menuSale {
            get {
                return ResourceManager.GetString("menuSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phút.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string nameProduct {
            get {
                return ResourceManager.GetString("nameProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có sản phẩm nào trong giỏ hàng của bạn. Hãy tiếp tục tìm kiếm sản phẩm bạn yêu thích, hoặc.
        /// </summary>
        internal static string noThing {
            get {
                return ResourceManager.GetString("noThing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string numberProduct {
            get {
                return ResourceManager.GetString("numberProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước.
        /// </summary>
        internal static string prev {
            get {
                return ResourceManager.GetString("prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết sản phẩm.
        /// </summary>
        internal static string productDetail {
            get {
                return ResourceManager.GetString("productDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giây.
        /// </summary>
        internal static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string sizeProduct {
            get {
                return ResourceManager.GetString("sizeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIỄN PHÍ GIAO HÀNG.
        /// </summary>
        internal static string title1 {
            get {
                return ResourceManager.GetString("title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANH TOÁN KHI NHẬN HÀNG.
        /// </summary>
        internal static string title2 {
            get {
                return ResourceManager.GetString("title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHIỀU CHƯƠNG TRÌNH ƯU ĐÃI.
        /// </summary>
        internal static string title3 {
            get {
                return ResourceManager.GetString("title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MỞ CỬA TẤT CẢ CÁC NGÀY TRONG TUẦN.
        /// </summary>
        internal static string title4 {
            get {
                return ResourceManager.GetString("title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm được quan tâm nhiều.
        /// </summary>
        internal static string titleBuy {
            get {
                return ResourceManager.GetString("titleBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức thanh toán.
        /// </summary>
        internal static string titleBuy1 {
            get {
                return ResourceManager.GetString("titleBuy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức vận chuyển.
        /// </summary>
        internal static string titleBuy2 {
            get {
                return ResourceManager.GetString("titleBuy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên người mua.
        /// </summary>
        internal static string titleBuy3 {
            get {
                return ResourceManager.GetString("titleBuy3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string titleBuy4 {
            get {
                return ResourceManager.GetString("titleBuy4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string titleBuy5 {
            get {
                return ResourceManager.GetString("titleBuy5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string titleBuy6 {
            get {
                return ResourceManager.GetString("titleBuy6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục sản phẩm.
        /// </summary>
        internal static string titleCatalog {
            get {
                return ResourceManager.GetString("titleCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thay đổi số lượng.
        /// </summary>
        internal static string titleChangeAmount {
            get {
                return ResourceManager.GetString("titleChangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cho chúng tôi biết suy nghĩ của bạn!.
        /// </summary>
        internal static string titleComment {
            get {
                return ResourceManager.GetString("titleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ ngay.
        /// </summary>
        internal static string titleContact {
            get {
                return ResourceManager.GetString("titleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa khỏi giỏ hàng.
        /// </summary>
        internal static string titleDelete {
            get {
                return ResourceManager.GetString("titleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        internal static string titleNew {
            get {
                return ResourceManager.GetString("titleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại mới.
        /// </summary>
        internal static string titleSale {
            get {
                return ResourceManager.GetString("titleSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để quay lại.
        /// </summary>
        internal static string toBack {
            get {
                return ResourceManager.GetString("toBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền đơn hàng.
        /// </summary>
        internal static string totalCart {
            get {
                return ResourceManager.GetString("totalCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string txtAddress {
            get {
                return ResourceManager.GetString("txtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail hoặc tên đăng nhập.
        /// </summary>
        internal static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string txtEmailRegister {
            get {
                return ResourceManager.GetString("txtEmailRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string txtName {
            get {
                return ResourceManager.GetString("txtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string txtPass {
            get {
                return ResourceManager.GetString("txtPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string txtPassRegister {
            get {
                return ResourceManager.GetString("txtPassRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string txtPhone {
            get {
                return ResourceManager.GetString("txtPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất liệu.
        /// </summary>
        internal static string typeProduct {
            get {
                return ResourceManager.GetString("typeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng của bạn.
        /// </summary>
        internal static string yourOrder {
            get {
                return ResourceManager.GetString("yourOrder", resourceCulture);
            }
        }
    }
}
